### ISSUE TITLE
doesn't build successfully on win10 with both msvc and gnu targets

### ISSUE THREAD

**Issue by omac777** [gnzlbg/jemallocator#133] opened 2019-09-05 19:30 UTC
I'm trying to build nom on win10 and jemallocator-sys is a dependency which fails to build.
Here is what I did:

```
C:\WINDOWS\system32>"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```

cd C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8>

```
cargo build --release --verbose --verbose --target=x86_64-pc-windows-gnu
error: failed to run custom build command for `jemalloc-sys v0.1.8 (C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8)`

Caused by:
  process didn't exit successfully: `C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8\target\release\build\jemalloc-sys-9566d0968475bffa\build-script-build` (exit code: 101)
--- stdout
TARGET=x86_64-pc-windows-gnu
HOST=x86_64-pc-windows-msvc
NUM_JOBS=4
OUT_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\x86_64-pc-windows-gnu\\release\\build\\jemalloc-sys-833b49275cddfd09\\out"
BUILD_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\x86_64-pc-windows-gnu\\release\\build\\jemalloc-sys-833b49275cddfd09\\out\\build"
SRC_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8"
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
TARGET_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
CC="gcc.exe"
CFLAGS="-O3 -ffunction-sections -fdata-sections -m64 -Wall"
JEMALLOC_SRC_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\x86_64-pc-windows-gnu\\release\\build\\jemalloc-sys-833b49275cddfd09\\out\\jemalloc"
cargo:rustc-cfg=prefixed
JEMALLOC PREFIX SET TO: _rjem_
running: "sh" "/c/Users/davidm/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.1.8/target/x86_64-pc-windows-gnu/release/build/jemalloc-sys-833b49275cddfd09/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_r
jem_" "--host=x86_64-w64-mingw32" "--build=x86_64-pc-win32" "--prefix=C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\x86_64-pc-windows-gnu\\release\\build\\jemalloc-sys-833b49275cddfd09\\out"
checking for xsltproc... false
checking for x86_64-w64-mingw32-gcc... gcc.exe
checking whether the C compiler works... no

--- stderr
configure: error: in `/c/Users/davidm/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.1.8/target/x86_64-pc-windows-gnu/release/build/jemalloc-sys-833b49275cddfd09/out/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
thread 'main' panicked at 'command did not execute successfully: "sh" "/c/Users/davidm/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.1.8/target/x86_64-pc-windows-gnu/release/build/jemalloc-sys-833b49275cddfd09/out/jemalloc/configure" "--disable-cxx" "--w
ith-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-w64-mingw32" "--build=x86_64-pc-win32" "--prefix=C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\x86_64-pc-windows-gnu\\release\\build\\jemallo
c-sys-833b49275cddfd09\\out"
expected success, got: exit code: 77', build.rs:289:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
cargo build --release --verbose --verbose
     Running `C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8\target\release\build\jemalloc-sys-9566d0968475bffa\build-script-build`
[jemalloc-sys 0.1.8] TARGET=x86_64-pc-windows-msvc
[jemalloc-sys 0.1.8] HOST=x86_64-pc-windows-msvc
[jemalloc-sys 0.1.8] NUM_JOBS=4
[jemalloc-sys 0.1.8] OUT_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\release\\build\\jemalloc-sys-da4c6f7da1e98082\\out"
[jemalloc-sys 0.1.8] BUILD_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\release\\build\\jemalloc-sys-da4c6f7da1e98082\\out\\build"
[jemalloc-sys 0.1.8] SRC_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8"
[jemalloc-sys 0.1.8] thread 'main' panicked at 'jemalloc does not support target: x86_64-pc-windows-msvc', build.rs:58:13
[jemalloc-sys 0.1.8] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: failed to run custom build command for `jemalloc-sys v0.1.8 (C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8)`

Caused by:
  process didn't exit successfully: `C:\Users\davidm\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8\target\release\build\jemalloc-sys-9566d0968475bffa\build-script-build` (exit code: 101)
--- stdout
TARGET=x86_64-pc-windows-msvc
HOST=x86_64-pc-windows-msvc
NUM_JOBS=4
OUT_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\release\\build\\jemalloc-sys-da4c6f7da1e98082\\out"
BUILD_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8\\target\\release\\build\\jemalloc-sys-da4c6f7da1e98082\\out\\build"
SRC_DIR="C:\\Users\\davidm\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8"

--- stderr
thread 'main' panicked at 'jemalloc does not support target: x86_64-pc-windows-msvc', build.rs:58:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by gnzlbg** [comment] 2019-09-06 12:26
Duplicate of #91

**Closed by gnzlbg** 2019-09-06 12:26 UTC
